PREFIX mns_1: <http://ts.tno.nl/mediator/1.0/examples/ontoTemp1A#> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> SELECT ?p ?t WHERE { ?p <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ts.tno.nl/mediator/1.0/examples/ontoTemp1A#Patient> . ?p <http://ts.tno.nl/mediator/1.0/examples/ontoTemp1A#hasTemp> ?t ; <http://ts.tno.nl/mediator/1.0/examples/ontoTemp1B#hasAge> ?a . FILTER ( ( ?t > 37.0 ) && ( ?a < 37 ) ) }