PREFIX mns_2: <http://ts.tno.nl/mediator/1.0/examples/ontoTemp1B#> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX foaf: <http://xmlns.com/foaf/0.1/> ASK { ?p <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ts.tno.nl/mediator/1.0/examples/ontoTemp1B#PatientNaam> . ?p <http://ts.tno.nl/mediator/1.0/examples/ontoTemp1B#temperature_inF> ?t . FILTER ( ?t > 98.6 ) }