# test query
PREFIX	ontoA:	<http://ts.tno.nl/mediator/1.0/examples/ontoTemp1A#>
PREFIX	ontoF:	<http://ts.tno.nl/mediator/1.0/examples/ontoFail#>
PREFIX	rdf:	<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf:   <http://xmlns.com/foaf/0.1/>

ASK  { 
    ?p rdf:type ontoA:Patient ;
	ontoF:hasTemp ?t.
	FILTER (?t > 37.0 )
} 