# test query
PREFIX	ontoNE:	<http://ts.tno.nl/mediator/1.0/examples/ontoNonExistent>
PREFIX	rdf:	<http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK  { 
    ?p rdf:type ontoNE:Patient .
	?p ontoNE:hasTemp ?t.
	FILTER (?t > 37.0 )
} 