# test query
PREFIX	ontoA:	<http://ts.tno.nl/mediator/1.0/examples/ontoTemp1A#>
PREFIX	rdf:	<http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?p ?t
WHERE {
    ?p rdf:type ontoA:Patient .
    ?r rdf:type ontoA:hasTemp.
	?p ontoA:hasTemp ?t.
	ontoA:hasTemp ?r ?t.
	FILTER (?t > 37.0  )
}


