# test query
PREFIX	ontoNE:	<http://ts.tno.nl/mediator/1.0/examples/ontoNonExistent>
PREFIX	rdf:	<http://www.w3.org/1999/02/22-rdf-syntax-ns>
PREFIX  xsd:	<http://www.w3.org/2001/XMLSchema>

SELECT ?p ?t
WHERE {
    ?p rdf:type ontoNE:Patient .
	?p ontoNE:hasTemp ?t;
	   ontoNE:hasAge ?a.
	FILTER ( 
		( DATATYPE ( ?t ) = xsd:float ) 
	)
}


